[package]
name = "dosegoose-uniffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "UniFFI adapter for the Dose Goose core"
publish = false

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
dosegoose.workspace = true
uniffi.workspace = true
uuid.workspace = true

[lints]
workspace = true
